name: Python package

on:
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:

    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
       behave Features/Dataaxel.feature
       behave Features/DataLogin.feature
       behave Features/Dataaxleforget.feature
